#---
server:
  port: 8761
spring:
#  profiles: peer1
  application:
    name: eureka-server
eureka:
  instance:
    hostname: peer1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
#      defaultZone: http://peer2:8762/eureka/

#---
#server:
#  port: 8762
#spring:
#  profiles: peer2
#  application:
#    name: eureka-server
#eureka:
#  instance:
#    hostname: peer2
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://peer1:8761/eureka/

#---
